{{ config(
  materialized = 'table', tags = [ 'stage' ]
) }} WITH raw_union AS (
  SELECT 
    COUNTRY, 
    CTY, 
    CTY_DESCR, 
    ATC1, 
    ATC2, 
    ATC3, 
    ATC4, 
    NULL AS INTWHOATC1, 
    NULL AS INTWHOATC2, 
    NULL AS INTWHOATC3, 
    NULL AS INTWHOATC4, 
    ATC4_DESCR, 
    MOL_LIST, 
    CRP, 
    NULL AS MNF, 
    INTPRD, 
    INTPCK, 
    NFC123, 
    INTSTR, 
    NULL AS INTWHOATC5, 
    NULL AS INTMNF, 
    SEMI_ETHICAL, 
    NULL AS INTRX, 
    'MIDAS_BOEHRINGER_DASS_BI_MTH' AS DS_NM 
  FROM 
    {{ source(
      'landing_iqvia', 'MIDAS_BOEHRINGER_DASS_BI_MTH_STG'
    ) }} 
  UNION ALL 
  SELECT 
    COUNTRY, 
    CTY, 
    CTY_DESCR, 
    ATC1, 
    ATC2, 
    ATC3, 
    ATC4, 
    NULL AS INTWHOATC1, 
    NULL AS INTWHOATC2, 
    NULL AS INTWHOATC3, 
    NULL AS INTWHOATC4, 
    ATC4_DESCR, 
    MOL_LIST, 
    CRP, 
    NULL AS MNF, 
    INTPRD, 
    INTPCK, 
    NFC123, 
    INTSTR, 
    NULL AS INTWHOATC5, 
    NULL AS INTMNF, 
    SEMI_ETHICAL, 
    NULL AS INTRX, 
    'MIDAS_BOEHRINGER_DASS_BI_QTR' AS DS_NM 
  FROM 
    {{ source(
      'landing_iqvia', 'MIDAS_BOEHRINGER_DASS_BI_QTR_STG'
    ) }} 
  UNION ALL 
  SELECT 
    COUNTRY, 
    CTY, 
    CTY_DESCR, 
    ATC1, 
    ATC2, 
    ATC3, 
    ATC4, 
    INTWHOATC1, 
    INTWHOATC2, 
    INTWHOATC3, 
    INTWHOATC4, 
    NULL AS ATC4_DESCR, 
    MOL_LIST, 
    CRP, 
    MNF, 
    INTPRD, 
    INTPCK, 
    NFC123, 
    INTSTR, 
    INTWHOATC5, 
    INTMNF, 
    NULL AS SEMI_ETHICAL, 
    INTRX, 
    'MIDAS_BOEHRINGER_DASS_BI_MTH_HQ' AS DS_NM 
  FROM 
    {{ source(
      'landing_iqvia', 'MIDAS_BOEHRINGER_DASS_BI_MTH_HQ_STG'
    ) }} 
  UNION ALL 
  SELECT 
    COUNTRY, 
    CTY, 
    CTY_DESCR, 
    ATC1, 
    ATC2, 
    ATC3, 
    ATC4, 
    INTWHOATC1, 
    INTWHOATC2, 
    INTWHOATC3, 
    INTWHOATC4, 
    NULL AS ATC4_DESCR, 
    MOL_LIST, 
    CRP, 
    MNF, 
    INTPRD, 
    INTPCK, 
    NFC123, 
    INTSTR, 
    INTWHOATC5, 
    INTMNF, 
    NULL AS SEMI_ETHICAL, 
    INTRX, 
    'MIDAS_BOEHRINGER_DASS_BI_QTR_HQ' AS DS_NM 
  FROM 
    {{ source(
      'landing_iqvia', 'MIDAS_BOEHRINGER_DASS_BI_QTR_HQ_STG'
    ) }}
), 
lookup_iso AS (
  SELECT 
    r.*, 
    c."ISO2_CODE" AS "ISO_GEO_ID" 
  FROM 
    raw_union r 
    LEFT JOIN {{ ref('dim_country') }} c ON UPPER(
      TRIM(r.COUNTRY)
    ) = UPPER(
      TRIM(c.NAME)
    )
), 
cleaned_union AS (
  SELECT 
    *, 
    COALESCE(ATC1, INTWHOATC1) AS CANONICAL_ATC1,
    COALESCE(ATC2, INTWHOATC2) AS CANONICAL_ATC2,
    COALESCE(ATC3, INTWHOATC3) AS CANONICAL_ATC3,
    COALESCE(ATC4, INTWHOATC4) AS CANONICAL_ATC4,
    CASE
      WHEN INTPCK IS NULL THEN NULL
      WHEN SEMI_ETHICAL IS NOT NULL THEN CASE WHEN UPPER(SEMI_ETHICAL) LIKE '%PRESCRIPTION MEDICINE%' THEN 'Y' ELSE 'N' END
      WHEN INTRX IS NOT NULL THEN CASE WHEN UPPER(INTRX) LIKE '%PRESCRIPTION%' THEN 'Y' ELSE 'N' END
      ELSE 'N'
    END AS PRESCRIPTION_REQUIRED_INDICATOR 
  FROM 
    lookup_iso
), 
brands AS (
  SELECT 
    DISTINCT MD5(
      CONCAT("ISO_GEO_ID", DS_NM, INTPRD)
    ) AS BUSINESS_KEY, 
    "ISO_GEO_ID" AS GEOGRAPHIC_ID, 
    'IQVIA_MIDAS' AS DATASET_ID, 
    DS_NM AS SOURCE_DATASET_ID, 
    COUNTRY AS SOURCE_COUNTRY_NAME,
    CTY AS SOURCE_COUNTRY_CODE,
    'Brand' AS PRODUCT_TYPE_CODE, 
    INTPRD AS PRODUCT_NAME, 
    INTPRD AS BRAND_NAME, 
    INTPRD AS SOURCE_PRODUCT_BRAND_ID, 
    NULL AS SOURCE_PRODUCT_PACK_ID, 
    SEMI_ETHICAL, 
    NULL AS SUBSTANCE, 
    CANONICAL_ATC1 AS ATC1, 
    CANONICAL_ATC2 AS ATC2, 
    CANONICAL_ATC3 AS ATC3, 
    CANONICAL_ATC4 AS ATC_CODE, 
    CANONICAL_ATC4 AS ATC4, 
    ATC4_DESCR,
    SUBSTR(INTWHOATC5, 1, 7) AS WHO_CODE, 
    NULL AS NFC_CODE, 
    CRP AS CORPORATION, 
    CASE WHEN UPPER(CRP) LIKE '%BOEHRINGER%' THEN 'N' ELSE 'Y' END AS COMPETITOR_INDICATOR, 
    NULL AS PRESCRIPTION_REQUIRED_INDICATOR, 
    MNF AS MANUFACTURER_CODE,
    INTMNF AS MANUFACTURER, 
    NULL AS STRENGTH, 
    NULL AS DOSE_FORM_CODE 
  FROM 
    cleaned_union 
  WHERE 
    INTPRD IS NOT NULL
), 
pmps AS (
  SELECT 
    DISTINCT MD5(
      CONCAT(
        "ISO_GEO_ID", DS_NM, INTPRD, INTPCK
      )
    ) AS BUSINESS_KEY, 
    "ISO_GEO_ID" AS GEOGRAPHIC_ID, 
    'IQVIA_MIDAS' AS DATASET_ID, 
    DS_NM AS SOURCE_DATASET_ID, 
    COUNTRY AS SOURCE_COUNTRY_NAME,
    CTY AS SOURCE_COUNTRY_CODE,
    'PMP' AS PRODUCT_TYPE_CODE, 
    CONCAT(INTPRD, ' ', INTPCK) AS PRODUCT_NAME, 
    INTPRD AS BRAND_NAME, 
    INTPRD AS SOURCE_PRODUCT_BRAND_ID, 
    INTPCK AS SOURCE_PRODUCT_PACK_ID, 
    SEMI_ETHICAL, 
    MOL_LIST AS SUBSTANCE, 
    CANONICAL_ATC1 AS ATC1, 
    CANONICAL_ATC2 AS ATC2, 
    CANONICAL_ATC3 AS ATC3, 
    CANONICAL_ATC4 AS ATC_CODE, 
    CANONICAL_ATC4 AS ATC4, 
    ATC4_DESCR,
    SUBSTR(INTWHOATC5, 1, 7) AS WHO_CODE, 
    NFC123 AS NFC_CODE, 
    CRP AS CORPORATION, 
    CASE WHEN UPPER(CRP) LIKE '%BOEHRINGER%' THEN 'N' ELSE 'Y' END AS COMPETITOR_INDICATOR, 
    PRESCRIPTION_REQUIRED_INDICATOR, 
    MNF AS MANUFACTURER_CODE,
    INTMNF AS MANUFACTURER, 
    INTSTR AS STRENGTH, 
    NFC123 AS DOSE_FORM_CODE 
  FROM 
    cleaned_union 
  WHERE 
    INTPCK IS NOT NULL
) 
SELECT 
  BUSINESS_KEY, 
  GEOGRAPHIC_ID, 
  DATASET_ID, 
  SOURCE_DATASET_ID, 
  SOURCE_COUNTRY_NAME,
  SOURCE_COUNTRY_CODE,
  PRODUCT_TYPE_CODE, 
  PRODUCT_NAME, 
  BRAND_NAME, 
  SOURCE_PRODUCT_BRAND_ID, 
  SOURCE_PRODUCT_PACK_ID, 
  SEMI_ETHICAL, 
  SUBSTANCE, 
  ATC1, 
  ATC2, 
  ATC3, 
  ATC_CODE, 
  ATC4, 
  ATC4_DESCR,
  WHO_CODE, 
  NFC_CODE, 
  CORPORATION, 
  COMPETITOR_INDICATOR, 
  PRESCRIPTION_REQUIRED_INDICATOR, 
  MANUFACTURER_CODE,
  MANUFACTURER, 
  STRENGTH, 
  DOSE_FORM_CODE 
FROM 
  brands 
UNION ALL 
SELECT 
  BUSINESS_KEY, 
  GEOGRAPHIC_ID, 
  DATASET_ID, 
  SOURCE_DATASET_ID, 
  SOURCE_COUNTRY_NAME,
  SOURCE_COUNTRY_CODE,
  PRODUCT_TYPE_CODE, 
  PRODUCT_NAME, 
  BRAND_NAME, 
  SOURCE_PRODUCT_BRAND_ID, 
  SOURCE_PRODUCT_PACK_ID, 
  SEMI_ETHICAL, 
  SUBSTANCE, 
  ATC1, 
  ATC2, 
  ATC3, 
  ATC_CODE, 
  ATC4, 
  ATC4_DESCR,
  WHO_CODE, 
  NFC_CODE, 
  CORPORATION, 
  COMPETITOR_INDICATOR, 
  PRESCRIPTION_REQUIRED_INDICATOR, 
  MANUFACTURER_CODE,
  MANUFACTURER, 
  STRENGTH, 
  DOSE_FORM_CODE 
FROM 
  pmps
