{{ config(materialized='table', schema='DW_DFHPMS2EU_SEMARCHY_SCHEMA') }}

{% set etl_batch_id = env_var('ETL_BATCH_ID', env_var('DBT_JOB_RUN_ID', invocation_id)) %}
 
select
    s.geographic_id,
    s.dataset_id,
    s.source_dataset_id,
    s.dataset_product_id,
    s.product_type_code,
    s.product_name,
    s.standardized_product_name,
    s.description,
    s.product_status_code,
    s.effective_date,
    s.end_date,
    s.brand_name,
    s.generic_names,
    s.approved_date,
    s.marketing_start_date,
    s.marketing_end_date,
    s.expiration_date,
    s.substance,
    s.dose_form_code,
    s.strength,
    s.route_of_administration_code,
    s.pharmaceutical_product_quantity,
    s.unit_of_presentation_code,
    s.primary_package_quantity,
    s.primary_package_type_code,
    s.secondary_package_quantity,
    s.secondary_package_type_code,
    s.package_quantity,
    s.shelf_life_quantity,
    s.shelf_life_unit_of_measure_code,
    s.sample_indicator,
    s.competitor_indicator,
    s.generic_indicator,
    s.prescription_required_indicator,
    s.atc_code,
    s.who_code,
    s.nfc_code,
    s.chc_nec_code,
    s.usc_code,
    s.manufacturer_id,
    s.manufacturer,
    s.corporation,
    s.daily_dosage_quantity,
    s.is_imported,
    s.generic_product_description,
    s.channel,
    s.chc_flag
from {{ ref('SAT_PRODUCT_FILE') }} s
where s.end_datetime is null
  and s.etl_batch_id = '{{ etl_batch_id }}'
