{{ config(materialized='table', tags=['mart']) }}

WITH stg AS (
    SELECT
        GEOGRAPHIC_ID,
        DATASET_ID,
        SOURCE_DATASET_ID,
        PRODUCT_TYPE_CODE,
        BUSINESS_KEY,
        SEMI_ETHICAL
    FROM {{ ref('stg_iqvia_midas') }}
),

final AS (
    SELECT
        DATASET_ID AS DATASET_ID,
        CASE
            WHEN PRODUCT_TYPE_CODE = 'Brand' THEN CONCAT('BRAND_', BUSINESS_KEY)
            ELSE BUSINESS_KEY
        END AS DATASET_PRODUCT_ID,
        'CHC_PRODUCT_FLAG' AS PRODUCT_ADDITIONAL_INFO_TYPE,
        CASE
            WHEN UPPER(COALESCE(SEMI_ETHICAL, '')) LIKE '%CHC%' THEN 'Y'
            ELSE 'N'
        END AS PRODUCT_ADDITIONAL_INFO_VALUE,
        GEOGRAPHIC_ID AS GEOGRAPHY,
        GEOGRAPHIC_ID AS COUNTRY_CODE,
        'A' AS STATUS_CODE,
        NULL::DATE AS EFFECTIVE_DATE,
        NULL::DATE AS END_DATE,
        SOURCE_DATASET_ID AS IDENTIFIER_TYPE_CODE
    FROM stg
)

SELECT
    DATASET_ID,
    DATASET_PRODUCT_ID,
    PRODUCT_ADDITIONAL_INFO_TYPE,
    PRODUCT_ADDITIONAL_INFO_VALUE,
    GEOGRAPHY,
    COUNTRY_CODE,
    STATUS_CODE,
    EFFECTIVE_DATE,
    END_DATE,
    IDENTIFIER_TYPE_CODE
FROM final
