{{ config(materialized='incremental', unique_key='HK_PRODUCT', tags=['vault']) }}

SELECT DISTINCT 
    MD5(UPPER(CONCAT(GEOGRAPHIC_ID, '_', SOURCE_DATASET_ID, '_', PRODUCT_NAME))) AS HK_PRODUCT,
    CONCAT(GEOGRAPHIC_ID, '_', SOURCE_DATASET_ID, '_', PRODUCT_NAME) AS BUSINESS_KEY,
    CURRENT_TIMESTAMP() AS LOAD_DATETIME,
    'IQVIA_MIDAS' AS RECORD_SOURCE
FROM {{ ref('stg_iqvia_midas') }}

{% if is_incremental() %}
    WHERE MD5(UPPER(CONCAT(GEOGRAPHIC_ID, '_', SOURCE_DATASET_ID, '_', PRODUCT_NAME))) NOT IN (SELECT HK_PRODUCT FROM {{ this }})
{% endif %}